# vim-like visual mode and copy/paste
set -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line

# ensure new windows open in the current directory
bind c new-window -c "#{pane_current_path}"
bind C new-window -c "#{pane_current_path}"

# Monitor activity in windows
setw -g monitor-activity on
set -g visual-activity on

# Highlight windows with activity in status bar
setw -g window-status-activity-style 'fg=red,bg=default'
